### ISSUE TITLE
ML Study 2021

### ISSUE THREAD

**Issue by dingdongx2** [BD-SEARCH/Study2019#2]
## Goal

ani2pic로 사진을 캐릭터로 변환하여 데이터를 생성하고, 이 캐릭터를 다시 사진으로 복구하는 모델을 만든다

### TODO - paper review

- [x] [VanillaGAN](https://22-22.tistory.com/36) 리뷰
- [x] [cGAN](https://22-22.tistory.com/81) 리뷰
- [x] pix2pix 리뷰
- [ ] CycleGAN 리뷰
- [ ] StyleGAN 리뷰

### ready for project

- [x] [toonify](https://github.com/justinpinkney/toonify) 로직 확인
- [x] https://www.artbreeder.com/
- [ ] 데이터 생성
- [ ] 모델 설계

**Comment by warmwall** [comment]
##  20210114

- 장소: 집

### 진행

- 오랜만의 스터디였기 때문에, 지난 상황 복기 및 계획 재정리

### 계획

- pix2pix 읽기
- pix2pix 관련 유투브 시청 : https://www.youtube.com/watch?v=BzObmqSexEA
- https://github.com/dingdongx2/Ani2Pic 참고하여 dataset 확정

**Comment by dingdongx2** [comment]
## 20210128
* 장소 : 원격

### 진행
* pix2pix 관련 블로그 정독
* ani2pic dataset 선정 : [1 million fake faces](https://archive.org/details/1mFakeFaces)

### 계획
* dataset download
```
wget https://archive.org/download/1mFakeFaces/1m_faces_01.tar
...
wget https://archive.org/download/1mFakeFaces/1m_faces_98.tar
wget https://archive.org/download/1mFakeFaces/1m_faces_99.tar
```
* toonify를 통해 GT 쌍 만들기

**Comment by dingdongx2** [comment]
## 20210206

* 장소 : 원격

### 진행
* toonify data download
  * s : 00 
  * w : 01
* toonify를 통한 GT 쌍 만들기 (코드 작성)

### 계획
* 쌍 만들어지면 결과 공유

**Comment by dingdongx2** [comment]
## 20210221
* 장소 : 원격

### 진행
* toonify code 재개
* pix2pix 논문리뷰 : https://22-22.tistory.com/82

### 계획
* GT쌍 만들기 완성 (과제)

**Comment by warmwall** [comment]
## 20210313

- 장소 : 강남역 스타벅스

### 진행

- toonify code 계속 돌리기
- lotto 플젝을 만들기 위한 기본 정보 수집 및 계획 수립

### 계획
- GT쌍 만들기 (분할)
- crawling code 작성

**Comment by dingdongx2** [comment]
## 20210328 
* 장소 : 원격

### 진행
* toonify
  * GT쌍 이어만들기
* cbWinner
  * base data 준비
  * baseline web 구성 : https://github.com/dingdongx2/could-be-a-winner

### 계획
* toonify
  * GT쌍 이어만들기
* cbWinner
  * 기능 추가

**Comment by warmwall** [comment]
## 20210425
* 장소 : 원격

### 진행
* toonify
  * GT쌍 이어만들기
* cbWinner
  * baseline web 구성 : https://dingdongx2.github.io/
  *  당첨 회차 표시 기능 추가

### 계획
* toonify
  * GT쌍 이어만들기
* cbWinner
  * 기능 추가
  * 디자인 개선
